import type { Metadata } from "next";
import "./globals.css";
import css from "./layout.module.css"
// import Sidebar from "../components/sidebar/page";



export const metadata: Metadata = {
  title: "Resume",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={css.body}>
        {/* <Sidebar />
        <main className="mainContainer">{children}</main> */}
        {children}
      </body>
    </html>
  );
}
