import type { Metadata } from "next";
import "./globals.css";
import css from "./layout.module.css"




export const metadata: Metadata = {
  title: "Resume",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={css.body}>
               {children}
      </body>
    </html>
  );
}
